/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SushiIndexRouteImport } from './routes/sushi/index'
import { Route as SouceIndexRouteImport } from './routes/souce/index'
import { Route as SnackIndexRouteImport } from './routes/snack/index'
import { Route as PizzaIndexRouteImport } from './routes/pizza/index'
import { Route as DrinkIndexRouteImport } from './routes/drink/index'
import { Route as DesertIndexRouteImport } from './routes/desert/index'
import { Route as ComboIndexRouteImport } from './routes/combo/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SushiIndexRoute = SushiIndexRouteImport.update({
  id: '/sushi/',
  path: '/sushi/',
  getParentRoute: () => rootRouteImport,
} as any)
const SouceIndexRoute = SouceIndexRouteImport.update({
  id: '/souce/',
  path: '/souce/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnackIndexRoute = SnackIndexRouteImport.update({
  id: '/snack/',
  path: '/snack/',
  getParentRoute: () => rootRouteImport,
} as any)
const PizzaIndexRoute = PizzaIndexRouteImport.update({
  id: '/pizza/',
  path: '/pizza/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkIndexRoute = DrinkIndexRouteImport.update({
  id: '/drink/',
  path: '/drink/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesertIndexRoute = DesertIndexRouteImport.update({
  id: '/desert/',
  path: '/desert/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboIndexRoute = ComboIndexRouteImport.update({
  id: '/combo/',
  path: '/combo/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combo/': typeof ComboIndexRoute
  '/desert/': typeof DesertIndexRoute
  '/drink/': typeof DrinkIndexRoute
  '/pizza/': typeof PizzaIndexRoute
  '/snack/': typeof SnackIndexRoute
  '/souce/': typeof SouceIndexRoute
  '/sushi/': typeof SushiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combo': typeof ComboIndexRoute
  '/desert': typeof DesertIndexRoute
  '/drink': typeof DrinkIndexRoute
  '/pizza': typeof PizzaIndexRoute
  '/snack': typeof SnackIndexRoute
  '/souce': typeof SouceIndexRoute
  '/sushi': typeof SushiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combo/': typeof ComboIndexRoute
  '/desert/': typeof DesertIndexRoute
  '/drink/': typeof DrinkIndexRoute
  '/pizza/': typeof PizzaIndexRoute
  '/snack/': typeof SnackIndexRoute
  '/souce/': typeof SouceIndexRoute
  '/sushi/': typeof SushiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combo/'
    | '/desert/'
    | '/drink/'
    | '/pizza/'
    | '/snack/'
    | '/souce/'
    | '/sushi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combo'
    | '/desert'
    | '/drink'
    | '/pizza'
    | '/snack'
    | '/souce'
    | '/sushi'
  id:
    | '__root__'
    | '/'
    | '/combo/'
    | '/desert/'
    | '/drink/'
    | '/pizza/'
    | '/snack/'
    | '/souce/'
    | '/sushi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComboIndexRoute: typeof ComboIndexRoute
  DesertIndexRoute: typeof DesertIndexRoute
  DrinkIndexRoute: typeof DrinkIndexRoute
  PizzaIndexRoute: typeof PizzaIndexRoute
  SnackIndexRoute: typeof SnackIndexRoute
  SouceIndexRoute: typeof SouceIndexRoute
  SushiIndexRoute: typeof SushiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sushi/': {
      id: '/sushi/'
      path: '/sushi'
      fullPath: '/sushi/'
      preLoaderRoute: typeof SushiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souce/': {
      id: '/souce/'
      path: '/souce'
      fullPath: '/souce/'
      preLoaderRoute: typeof SouceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snack/': {
      id: '/snack/'
      path: '/snack'
      fullPath: '/snack/'
      preLoaderRoute: typeof SnackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pizza/': {
      id: '/pizza/'
      path: '/pizza'
      fullPath: '/pizza/'
      preLoaderRoute: typeof PizzaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink/': {
      id: '/drink/'
      path: '/drink'
      fullPath: '/drink/'
      preLoaderRoute: typeof DrinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desert/': {
      id: '/desert/'
      path: '/desert'
      fullPath: '/desert/'
      preLoaderRoute: typeof DesertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/': {
      id: '/combo/'
      path: '/combo'
      fullPath: '/combo/'
      preLoaderRoute: typeof ComboIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComboIndexRoute: ComboIndexRoute,
  DesertIndexRoute: DesertIndexRoute,
  DrinkIndexRoute: DrinkIndexRoute,
  PizzaIndexRoute: PizzaIndexRoute,
  SnackIndexRoute: SnackIndexRoute,
  SouceIndexRoute: SouceIndexRoute,
  SushiIndexRoute: SushiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
